### ISSUE TITLE
v1 Checklist

### ISSUE THREAD

**Issue by MaheshtheDev** [MaheshtheDev/fast-pwa#1]
- [x] Update ReadMe
- [x] Add Manifest for PWA
- [x] Hooks (isOffline, isPWAInstalled)
- [ ] Support for Push Notifications
